# This is a basic workflow to help you get started with Actions

name: CI
on: push 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12
    - name: Install Npm models
      run: npm install
    - name: Build React App
      run: npm run build
    - name: Install Surge
      run: npm install -g surge
    - name: Run surge
      run: surge ./build http://expense-tracker-msusman.surge.sh/ --token ${{ secrets.SURGE_TOKEN }}
